# Generated by Django 5.2.5 on 2025-08-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cours_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
