# Generated by Django 5.2.5 on 2025-08-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cours_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='description',
        ),
        migrations.AddField(
            model_name='seance',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
